M48
; DRILL file {KiCad 8.0.4} date 2025-01-26T22:49:18-0500
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-01-26T22:49:18-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.4
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.1575
%
G90
G05
T1
X3.6846Y-2.0575
X3.6846Y-2.285
T2
X3.8012Y-1.876
X3.8012Y-2.4646
T3
X1.8438Y-2.1685
X2.5938Y-2.1685
X3.3438Y-2.1685
M30
